spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: my-topic

management:
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    org.apache.kafka: error